### ISSUE TITLE
http://tyloo/admin/tags

### ISSUE THREAD

**Issue by yuri25** [tyloo/tyloo#18] opened 2016-04-21 01:14 UTC
Whoops, looks like something went wrong.

2/2
ErrorException in compiled.php line 9534:
Route [works.tag] not defined. (View: C:\OpenServer\domains\tyloo\resources\views\backend\tags\index.blade.php)
in compiled.php line 9534
at CompilerEngine->handleViewException(object(InvalidArgumentException), '0') in compiled.php line 15076
at PhpEngine->evaluatePath('C:\OpenServer\domains\tyloo\storage\framework\views/a35e277404d39d5c34d4d04007462e8ecc47c5e0.php', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'tags' => object(Collection), 'user' => object(User))) in compiled.php line 15111

InvalidArgumentException in compiled.php line 9534:
Route [works.tag] not defined.
in compiled.php line 9534
at UrlGenerator->route('works.tag', 'teg', true, null) in helpers.php line 620
at route('works.tag', 'teg') in a35e277404d39d5c34d4d04007462e8ecc47c5e0.php line 26
at include('C:\OpenServer\domains\tyloo\storage\framework\views\a35e277404d39d5c34d4d04007462e8ecc47c5e0.php') in compiled.php line 15074

**Comment by tyloo** [comment] 2016-04-21 09:10
I can't reproduce it. Maybe you are not up-to-date with the last version. I'll close this and feel free to reopen it if you have more informations.

**Closed by tyloo** 2016-04-21 09:10 UTC
Labels: bug
